repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: \.py$  # Handled by ruff
      - id: end-of-file-fixer
        exclude: \.py$  # Handled by ruff
      - id: check-yaml
        args: [--unsafe] # syntax-only check. Seed files use custom YAML tags
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
        args: [--maxkb=1000]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.12
    hooks:
      - id: actionlint

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check --fix --show-fixes
        language: system
        types: [python]
        pass_filenames: true

      - id: ruff-format
        name: ruff format
        entry: uv run ruff format
        language: system
        types: [python]
        pass_filenames: true

      #- id: mypy
      #  name: mypy
      #  entry: uv run mypy --show-traceback
      #  language: system
      #  types: [python]
      #  pass_filenames: true
      #  require_serial: true

      - id: pip-audit
        name: pip-audit
        entry: uv run pip-audit
        language: system
        pass_filenames: false
        files: ^(pyproject\.toml|uv\.lock)$
